phosphene_generator:
  percept_model: scoreboard
  percept_model_args:
    xrange: [-2, 2]
    yrange: [-2, 2]
    xystep: 0.15
    rho: 75
  implant: PRIMA75
  implant_args:
    z: 0
  dataset: MNIST

classifier_evaluator:
  classifier: basic_cnn

pretrained_classifier: Out/prima75scoreboard4/final_model.h5